### ISSUE TITLE
Width used on Kindle is not respecting width of PNG

### ISSUE THREAD

**Issue by aptonline** [lanrat/hass-kindle-screensaver#1]
As noted here:

https://github.com/lanrat/hass-screenshot/issues/3

The width on the given image is not respected and shown correctly on the Kindle.  If the width is say 500px it still appears to be showing as 600px on the kindle.

**Comment by lanrat** [comment]
This tool was deigned to show images that are the native resolution of the kindle's display. So you have a few onions to accomplish what you want:

1. Use ImageMagick on the hass-screenshot service to add padding to the screenshot you are taking to make it the correct size for the kindle's display.
2. Add the ability to specify an alignment to fbink when rendering an image with a non-native resolution to this screensaver.

If you want to go with option 2, you can add the correct alignment arguments to [fbink here](https://github.com/lanrat/hass-kindle-screensaver/blob/6dd21c736b1cb8224460215d0a29dd31d8cdd163/extensions/homeassistant/script.sh#L196). See this [doc](https://github.com/lanrat/hass-kindle-screensaver/blob/main/doc/fbink.txt) for fbink options.

As this is a feature request that is outside of the initial scope of this project, I'm going to close this issue, but feel free to respond here if you have more questions. If you do make the change for option 2 and make it configureable, I'll happily accept a PR to merge it.

**Comment by aptonline** [comment]
Thanks @lanrat , can I ask what the point of `RENDERING_SCREEN_WIDTH` and `RENDERING_SCREEN_HEIGHT` Is in the docker if not to adjust how the image is generated and therefore displayed? A little confused. Surely the Kindle should display what is presented to it.

as mentioned `RENDERING_SCREEN_HEIGHT` does seem to work it’s the width that not.

**Comment by lanrat** [comment]
`RENDERING_SCREEN_WIDTH` and `RENDERING_SCREEN_HEIGHT` control the size of the headless chrome instance used when taking the screenshot and are effectively setting the resulting image size.

If I'm understanding your problem correctly, you are trying to display an image that is smaller than the screen size. This is currently an undefined behavior. However you can tell fbink how to handle it as I mentioned in the prior comment.

**Comment by aptonline** [comment]
Hi @lanrat , I’ve come up with a more elegant solution to address the issue.  If you use the `custom:vertical-stack-in-card` card in home assistant you can add padding to the right edge of the main card as below:

```
type: custom:vertical-stack-in-card
style: |
  ha-card {
    padding-right:45px;
  }
```

This keeps the card at the correct size 800x600 but added the required padding.

Down side is that there is no visual editor for this custom card so you need to add the changes manually after you are happy with the overall card design.

Hope this helps helps someone else.

Thanks for your help.

**Comment by lanrat** [comment]
Thanks for sharing. I'm glad you found a solution that works for you!
